### ISSUE TITLE
arm 架构的cpu无法安装成功

### ISSUE THREAD

**Issue by zhumao520** [H-T-H/Gemini-Telegram-Bot#2]
能做一个arm架构的镜像吗

**Comment by ferstar** [comment]
自己打包个又不是啥难事，或者直接跑也OK

**Comment by H-T-H** [comment]
> 能做一个arm架构的镜像吗

已完成，使用以下命令安装：
docker run -d -e TELEGRAM_BOT_API_KEY={replace with your Telegram Bot API} -e GEMINI_API_KEYS={replace with your Gemini API keys} qwqhthqwq/gemini_telegram_bot_arm:latest
