### ISSUE TITLE
你好兄弟

### ISSUE THREAD

**Issue by zhumao520** [H-T-H/Gemini-Telegram-Bot#5]
好像原作者把这个和bing 合拼在一起了你能不能一块更新  如果有时间的话  不过你这个也已经做的不错了 还是要感谢你 提供这么好的东西

**Comment by H-T-H** [comment]
你说的是哪个项目

**Comment by H-T-H** [comment]
找到你说的了，建议分两个机器人分别部署

**Comment by H-T-H** [comment]
https://x.com/yihong0618/status/1737115764837253366
原作者有个答复可以看一下解释
