### ISSUE TITLE
我太菜了

### ISSUE THREAD

**Issue by duckABC** [H-T-H/Gemini-Telegram-Bot#6]
大佬，我弄到第四步：python main.py ${Telegram 机器人 API} ${Gemini API 密钥}，执行这个代码时就开始报错了。

**Comment by H-T-H** [comment]
python main.py ${Telegram 机器人 API} ${Gemini API 密钥}
这条命令的意思是将“${Telegram 机器人 API}”这整个字符串，包括'$'和括号都替换成你的机器人API。

**Comment by duckABC** [comment]
原来是这样，谢谢佬。
