### ISSUE TITLE
Is it possible to deploy to Vercel? Zeabur is going to charge a fee.

### ISSUE THREAD

**Issue by vsd269** [H-T-H/Gemini-Telegram-Bot#9]
Is it possible to deploy to Vercel? Zeabur is going to charge a fee.

**Comment by H-T-H** [comment]
> Is it possible to deploy to Vercel? Zeabur is going to charge a fee.

It seems that is not possible.

**Comment by H-T-H** [comment]
You can try railway, which support docker.

**Comment by H-T-H** [comment]
[![Deploy on Railway](https://railway.app/button.svg)](https://railway.app/template/HIsbMv?referralCode=4LyW6R)

Just made a template, you can try it

**Comment by vsd269** [comment]
> [<img alt="Deploy on Railway" width="183" height="40" src="https://camo.githubusercontent.com/d07713342bc583232f8752c33a6a24e5f367d73725183a63f2f5fdd7c00606a3/68747470733a2f2f7261696c7761792e6170702f627574746f6e2e737667">](https://railway.app/template/HIsbMv?referralCode=4LyW6R)
> 
> 刚刚做了一个模板，你可以试试

![image](https://github.com/H-T-H/Gemini-Telegram-Bot/assets/142389217/616426b5-ed99-45a0-a977-4633240316d3)
I am having some issues and need your help

**Comment by H-T-H** [comment]
Hello vsd269,

Thank you for trying out the template! I'm here to help you with any issues you're having. To assist me better, please provide the following information:

Specific errors or problems you're encountering: Please include any error messages or unexpected behavior.
Steps to reproduce the issues: Describe the actions you take that lead to the problem.
Relevant code snippets or screenshots (if applicable): This will help me visualize the problem.
Once I have this information, I'll be able to troubleshoot effectively.

**Comment by vsd269** [comment]
> 你好vsd269，
> 
> 感谢您尝试该模板！我来这里是为了帮助您解决遇到的任何问题。为了更好地帮助我，请提供以下信息：
> 
> 您遇到的具体错误或问题：请包含任何错误消息或意外行为。 重现问题的步骤：描述您采取的导致问题的操作。 相关代码片段或屏幕截图（如果适用）：这将帮助我可视化问题。 一旦掌握了这些信息，我就能有效地排除故障。

https://github.com/H-T-H/Gemini-Telegram-Bot/assets/142389217/0e3d7b36-d8a2-4932-97e8-e6ea9492aa37

**Comment by vsd269** [comment]
I would appreciate it if you could help me figure out what the problem is. Thank you for your time.

**Comment by H-T-H** [comment]
https://docs.railway.app/reference/pricing

Free Trial
New users can take the platform for a spin by starting a free trial. The trial gives access to basic features and includes a one-time grant of $5.

Full vs Limited Trial

Your trial experience depends on whether Railway can verify your account. Read more about verification here.

Full Trial users can deploy code and databases, while Limited Trial users can only deploy databases.
